version: '3.3'

services:
  webserver:
    build: .
    ports:
      - "80:80"
    links:
      - mysql:mysql
    restart: always
    volumes:
      - ./html:/var/www/html/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpass'
      MYSQL_USER: 'testuser'
      MYSQL_PASSWORD: 'testpass'
      MYSQL_DATABASE: 'testdb'
    volumes:
      - ./data:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    ports:
            - "8000:80"
    environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
    links:
            - mysql
